### ISSUE TITLE
bug playback

### ISSUE THREAD

**Issue by golle15** [MrKrabat/plugin.video.watchbox#3]
Hey MrKrabat, seit 2 tagen läuft watchbox bei mir überhaupt nicht mehr. Komme bis zum Serien- Filmnamen der playback läuft jedoch nicht. Vor kurzem war das nur bei neu hochgeladen filmen / serien nun sind es alle.   

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/golle/.kodi/addons/plugin.video.watchbox/default.py", line 35, in <module>
                                                watchbox.main(sys.argv)
                                              File "/home/golle/.kodi/addons/plugin.video.watchbox/resources/lib/watchbox.py", line 48, in main
                                                check_mode(args)
                                              File "/home/golle/.kodi/addons/plugin.video.watchbox/resources/lib/watchbox.py", line 90, in check_mode
                                                controller.startplayback(args)
                                              File "/home/golle/.kodi/addons/plugin.video.watchbox/resources/lib/controller.py", line 380, in startplayback
                                                matches = re.search(regex, html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--

**Comment by Abbaddon911** [comment]
Gleiches hier, seit dem 11.7.2018 um etwa 5:30 morgens ist alles tot.

Hoffe da lässt sich was machen, ich sterbe ohne meinen Anime-Fix :D

**Comment by MrKrabat** [comment]
Hab einen Fix erstellt, Watchbox hatte was umgestellt :)

**Comment by golle15** [comment]
Das ging schnell danke :-)
